services:
  ftp_service:
    container_name: ftp-service
    build:
      context: .
      dockerfile: ftp-service.Dockerfile
    image: ftp-service-img
    restart: always
    ports:
      - "${FTP_SERVER_PORT}:${FTP_SERVER_PORT}"
    environment:
      - TZ=${TZ}
      - FTP_SERVER_PORT=${FTP_SERVER_PORT}
      - FTP_SPRING_APPLICATION_NAME=${FTP_SPRING_APPLICATION_NAME}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - EUREKA_HEALTHCHECK_ENABLED=${EUREKA_HEALTHCHECK_ENABLED}
      - EUREKA_INSTANCE_PREFER_IP=${EUREKA_INSTANCE_PREFER_IP}
      - EUREKA_LEASE_RENEWAL_INTERVAL=${EUREKA_LEASE_RENEWAL_INTERVAL}
      - EUREKA_LEASE_EXPIRATION_DURATION=${EUREKA_LEASE_EXPIRATION_DURATION}
      - FTP_HOST=${FTP_HOST}
      - FTP_PORT=${FTP_PORT}
      - FTP_USERNAME=${FTP_USERNAME}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - FTP_REMOTE_DIRECTORY=${FTP_REMOTE_DIRECTORY}
      - FTP_LOCAL_DIRECTORY=${FTP_LOCAL_DIRECTORY}
    networks:
      - term-project-net

networks:
  term-project-net:
    name: term-project-net
    driver: bridge