services:
  ftp_service:
    container_name: ftp-service
    build:
      context: .
      dockerfile: ftp-service.Dockerfile
    image: ftp-service-img
    restart: always
    ports:
      - "${FTP_SERVER_PORT}:${FTP_SERVER_PORT}"
    environment:
      - FTP_SERVER_PORT=${FTP_SERVER_PORT}
      - FTP_SPRING_APPLICATION_NAME=${FTP_SPRING_APPLICATION_NAME}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - EUREKA_HEALTHCHECK_ENABLED=${EUREKA_HEALTHCHECK_ENABLED}
      - EUREKA_INSTANCE_PREFER_IP=${EUREKA_INSTANCE_PREFER_IP}
      - EUREKA_LEASE_RENEWAL_INTERVAL=${EUREKA_LEASE_RENEWAL_INTERVAL}
      - EUREKA_LEASE_EXPIRATION_DURATION=${EUREKA_LEASE_EXPIRATION_DURATION}
      - FTP_HOST=${FTP_HOST}
      - FTP_PORT=${FTP_PORT}
      - FTP_USERNAME=${FTP_USERNAME}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - FTP_REMOTE_DIRECTORY=${FTP_REMOTE_DIRECTORY}
      - FTP_LOCAL_DIRECTORY=${FTP_LOCAL_DIRECTORY}
      - TZ=${TZ}
      - JASYPT_ENCRYPTOR_KEY=${JASYPT_ENCRYPTOR_KEY}
      - KAFKA_BOOTSTRAP_SERVERS_1=${KAFKA_BOOTSTRAP_SERVERS_1}
      - KAFKA_BOOTSTRAP_SERVERS_2=${KAFKA_BOOTSTRAP_SERVERS_2}
      - KAFKA_BOOTSTRAP_SERVERS_3=${KAFKA_BOOTSTRAP_SERVERS_3}
    volumes:
      - ftp_metadata:/metadata/store # 메타데이터 디렉토리 볼륨 마운트
    networks:
      - term-project-net

volumes:
  ftp_metadata:
    driver: local

networks:
  term-project-net:
    name: term-project-net
    driver: bridge