services:
  # PostgreSQL 설정
  postgresql_service:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    ports:
      - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}  # PostgreSQL 사용자 이름
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}  # PostgreSQL 사용자 비밀번호
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}     # 기본으로 생성할 데이터베이스 이름
    volumes:
      - postgres_data:/bitnami/postgresql  # 데이터 영속성을 위한 볼륨 설정
    networks:
      - term-project-net

  # Zookeeper 설정
  zookeeper_service:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    networks:
      - term-project-net

  # kafka-1 설정
  kafka-1_service:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    restart: always
    depends_on:
      - zookeeper_service
    ports:
      - "${KAFKA_1_PORT}:${KAFKA_1_PORT}"
    environment:
      TZ: ${TZ}
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID_1}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:${KAFKA_INTERNAL_PORT_1},EXTERNAL://localhost:${KAFKA_1_PORT} # Kafka 브로커의 내부 및 외부 통신 포트 설정: INTERNAL은 브로커 간 통신용, EXTERNAL은 외부 클라이언트용
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${KAFKA_DEFAULT_REPLICATION_FACTOR} # 자동으로 생성되는 topic의 기본 복제 수 (브로커수)
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
      KAFKA_LOG_RETENTION_HOURS: ${KAFKA_LOG_RETENTION_HOURS} # 메시지 보존 기간 설정
      KAFKA_COMPRESSION_TYPE: ${KAFKA_COMPRESSION_TYPE} # 메시지 압축 방식 설정
      KAFKA_SEGMENT_BYTES: ${KAFKA_SEGMENT_BYTES} # 로그 세그먼트 크기
      KAFKA_HEAP_OPTS: ${KAFKA_HEAP_OPTS} # JVM 힙 메모리 설정
    networks:
      - term-project-net

  # kafka-2 설정
  kafka-2_service:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    restart: always
    depends_on:
      - zookeeper_service
    ports:
      - "${KAFKA_2_PORT}:${KAFKA_2_PORT}"
    environment:
      TZ: ${TZ}
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID_2}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:${KAFKA_INTERNAL_PORT_2},EXTERNAL://localhost:${KAFKA_2_PORT}
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${KAFKA_DEFAULT_REPLICATION_FACTOR}
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
      KAFKA_LOG_RETENTION_HOURS: ${KAFKA_LOG_RETENTION_HOURS}
      KAFKA_COMPRESSION_TYPE: ${KAFKA_COMPRESSION_TYPE}
      KAFKA_SEGMENT_BYTES: ${KAFKA_SEGMENT_BYTES} 
      KAFKA_HEAP_OPTS: ${KAFKA_HEAP_OPTS}
    networks:
      - term-project-net

  # kafka-3 설정
  kafka-3_service:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-3
    restart: always
    depends_on:
      - zookeeper_service
    ports:
      - "${KAFKA_3_PORT}:${KAFKA_3_PORT}"
    environment:
      TZ: ${TZ}
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID_3}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:${KAFKA_INTERNAL_PORT_3},EXTERNAL://localhost:${KAFKA_3_PORT}
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${KAFKA_DEFAULT_REPLICATION_FACTOR}
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
      KAFKA_LOG_RETENTION_HOURS: ${KAFKA_LOG_RETENTION_HOURS}
      KAFKA_COMPRESSION_TYPE: ${KAFKA_COMPRESSION_TYPE}
      KAFKA_SEGMENT_BYTES: ${KAFKA_SEGMENT_BYTES} 
      KAFKA_HEAP_OPTS: ${KAFKA_HEAP_OPTS}
    networks:
      - term-project-net

  # kafka-ui 설정
  kafka-ui_service:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    restart: always
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      TZ: ${TZ}
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTER_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_UI_BOOTSTRAP_SERVERS}
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:${ZOOKEEPER_CLIENT_PORT}
    networks:
      - term-project-net

  # MongoDB 설정
  mongodb_service:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - term-project-net

  # Kafka Connect with Debezium
  kafka-connect_service:
    image: debezium/connect:2.7.3.Final
    container_name: kafka-connect
    restart: always
    depends_on:
      - kafka-1_service
      - zookeeper_service
    ports:
      - "${KAFKA_CONNECT_PORT}:${KAFKA_CONNECT_PORT}"  # Kafka Connect REST API
    environment:
      BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29093,kafka-3:29094
      GROUP_ID: ${KAFKA_CONNECT_GROUP_ID}
      CONFIG_STORAGE_TOPIC: ${KAFKA_CONNECT_CONFIG_STORAGE_TOPIC}
      OFFSET_STORAGE_TOPIC: ${KAFKA_CONNECT_OFFSET_STORAGE_TOPIC}
      STATUS_STORAGE_TOPIC: ${KAFKA_CONNECT_STATUS_STORAGE_TOPIC}
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER_SCHEMAS_ENABLE: false
      KEY_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_PLUGIN_PATH: ${KAFKA_CONNECT_PLUGIN_PATH}
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_REST_CORS_ALLOW_ORIGINS: "http://localhost:8084"  # Debezium UI의 호스트
      CONNECT_REST_CORS_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
    networks:
      - term-project-net

  # Debezium
  debezium-ui_service:
    image: debezium/debezium-ui:latest
    container_name: debezium-ui
    restart: always
    depends_on:
      - kafka-connect_service
    ports:
      - "8989:${DEBEZIUM_UI_PORT}"  # Debezium UI
    environment:
      KAFKA_CONNECT_URIS: "http://kafka-connect:8083"  # 내부 Kafka Connect URL
    networks:
      - term-project-net

volumes:
  postgres_data:
  mongodb_data:

networks:
  term-project-net:
    name: term-project-net
    driver: bridge