server:
  port: ${FTP_SERVER_PORT}  # .env 파일에서 포트를 주입받음

spring:
  application:
    name: ${FTP_SPRING_APPLICATION_NAME}  # .env 파일에서 서비스 이름을 주입받음

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}  # .env 파일에서 Eureka 서버 URL 주입
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP}  # 호스트명 사용 설정
    leaseRenewalIntervalInSeconds: ${EUREKA_LEASE_RENEWAL_INTERVAL}  # 갱신 빈도
    leaseExpirationDurationInSeconds: ${EUREKA_LEASE_EXPIRATION_DURATION}  # 만료 시간

ftp:
  host: ${FTP_HOST}  # FTP 서버 정보 주입
  port: ${FTP_PORT}
  username: ${FTP_USERNAME}
  password: ${FTP_PASSWORD}
  remote-directory: ${FTP_REMOTE_DIRECTORY}
  local-directory: ${FTP_LOCAL_DIRECTORY}
