services:
  data_service:
    container_name: data-service
    build:
      context: .
      dockerfile: data-service.Dockerfile
    image: data-service-img
    restart: always
    ports:
      - "${DATA_SERVER_PORT}:${DATA_SERVER_PORT}"
    environment:
      - DATA_SERVER_PORT=${DATA_SERVER_PORT}
      - DATA_SPRING_APPLICATION_NAME=${DATA_SPRING_APPLICATION_NAME}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - EUREKA_HEALTHCHECK_ENABLED=${EUREKA_HEALTHCHECK_ENABLED}
      - EUREKA_INSTANCE_PREFER_IP=${EUREKA_INSTANCE_PREFER_IP}
      - EUREKA_LEASE_RENEWAL_INTERVAL=${EUREKA_LEASE_RENEWAL_INTERVAL}
      - EUREKA_LEASE_EXPIRATION_DURATION=${EUREKA_LEASE_EXPIRATION_DURATION}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
      - JASYPT_ENCRYPTOR_KEY=${JASYPT_ENCRYPTOR_KEY}
      - KAFKA_BOOTSTRAP_SERVERS_1=${KAFKA_BOOTSTRAP_SERVERS_1}
      - KAFKA_BOOTSTRAP_SERVERS_2=${KAFKA_BOOTSTRAP_SERVERS_2}
      - KAFKA_BOOTSTRAP_SERVERS_3=${KAFKA_BOOTSTRAP_SERVERS_3}
      - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
    networks:
      - term-project-net

networks:
  term-project-net:
    name: term-project-net
    driver: bridge