services:
  service_discovery:
    container_name: eureka-server
    build:
      context: .
      dockerfile: service-discovery.Dockerfile
    image: service-discovery-img
    restart: always
    ports:
      - "${SERVICE_DISCOVERY_SERVER_PORT}:${SERVICE_DISCOVERY_SERVER_PORT}"
    environment:
      - TZ=${TZ}
      - SERVICE_DISCOVERY_SERVER_PORT=${SERVICE_DISCOVERY_SERVER_PORT}
      - EUREKA_INSTANCE_HOSTNAME=${EUREKA_INSTANCE_HOSTNAME}
      - ENABLE_SELF_PRESERVATION=${ENABLE_SELF_PRESERVATION}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
    networks:
      - term-project-net

networks:
  term-project-net:
    name: term-project-net
    driver: bridge