variables:
  SERVICE_INFRA_PATH: "./React-Project/CICD"

stages:
  - deploy

# 인프라 관련 배포 작업
deploy_infra:
  stage: deploy
  script:
    - echo "인프라 관련 설정 도커 컨테이너 배포 중..."
    - cd $SERVICE_INFRA_PATH
    
    # PostgreSQL 컨테이너 실행 상태 확인
    - echo "PostgreSQL 컨테이너 실행 상태 확인 중..."
    - export isPostgresRunning=$(docker ps --filter name=postgresql --filter status=running --format '{{.Names}}')
    - echo "PostgreSQL 실행 상태: ${isPostgresRunning}"
  # only:
  #   changes:
  #     - React-Project/BackEnd/**  # 백엔드 폴더 내 변경 사항이 있을 때만 배포 수행
