# 공통 변수 설정: CICD (인프라 관련) 경로를 변수로 지정하여 여러 곳에서 사용할 수 있도록 설정
variables:
  SERVICE_INFRA_PATH: "./React-Project/CICD"

# 파이프라인에서 사용할 스테이지들 정의: 빌드, 테스트, 배포 단계로 구성
stages: 
  # - build
  # - test
  - deploy

# 인프라 관련 배포 작업
deploy_infra:
  stage: deploy
  script:
    - echo "인프라 관련 설정 도커 컨테이너 배포 중..."
    - cd $SERVICE_INFRA_PATH
    
    # PostgreSQL 컨테이너 실행 상태 확인
    - echo "PostgreSQL Docker Container Running..."
    - export isPostgresRunning=$(docker ps --filter name=postgresql --filter status=running --format '{{.Names}}')
    - echo "PostgreSQL Running Check: ${isPostgresRunning}"
  # only:
  #   changes:
  #     - React-Project/BackEnd/**  # 백엔드 폴더 내 변경 사항이 있을 때만 배포 수행
